swagger: "2.0"
info:
  description: "This is a documentation for shop-info-service."
  version: "1.0.0"
  title: "Swagger Book store"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "Products"
      summary: "Gives list of product"
      description: "Returns an array of product's information"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductsList"
        "404":
          description: "Product list not found"
        "500":
          description: "Internal Server Error"
  /products/{id}:
    get:  
      tags:
      - "Products"
      summary: "Find products by id"
      description: "Returns a product's information"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Product's id"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "Product not found"
        "500":
          description: "Internal Server Error"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      count:
        type: "integer"
        format: "int32"
      description:
        type: "string"
        format: "byte"
      title:
        type: "string"
        format: "byte"
      price:
        type: "integer"
        format: "int32"
  ProductsList:
    type: "array"
    items:      
      $ref: "#/definitions/Product"
